# Только для получения сертификата: порт 80 + .well-known
server {
    listen 80;
    listen [::]:80;
    server_name agent.happybanana.solutions;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }
    location / {
        return 404;
    }
}
